/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface LSP11SocialRecoveryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COMMITMEMT_DELAY"
      | "DEFAULT_RECOVERY_DELAY"
      | "addGuardian"
      | "batchCalls"
      | "cancelRecoveryProcess"
      | "commitToRecover"
      | "executeRelayCall"
      | "executeRelayCallBatch"
      | "getCommitmentInfoOf"
      | "getFirstRecoveryTimestampOf"
      | "getGuardiansOf"
      | "getGuardiansThresholdOf"
      | "getNonce"
      | "getRecoveryCounterOf"
      | "getRecoveryDelayOf"
      | "getSecretHashOf"
      | "getVotedAddressByGuardian"
      | "getVotesOfGuardianVotedAddress"
      | "hasReachedThreshold"
      | "isGuardianOf"
      | "recoverAccess"
      | "removeGuardian"
      | "setGuardiansThreshold"
      | "setRecoveryDelay"
      | "setRecoverySecretHash"
      | "supportsInterface"
      | "voteForRecovery"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GuardianAdded"
      | "GuardianRemoved"
      | "GuardianVotedFor"
      | "GuardiansThresholdChanged"
      | "RecoveryCancelled"
      | "RecoveryDelayChanged"
      | "RecoveryProcessSuccessful"
      | "SecretHashChanged"
      | "SecretHashCommitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COMMITMEMT_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_RECOVERY_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addGuardian",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchCalls",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelRecoveryProcess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commitToRecover",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeRelayCall",
    values: [BytesLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeRelayCallBatch",
    values: [
      BytesLike[],
      BigNumberish[],
      BigNumberish[],
      BigNumberish[],
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommitmentInfoOf",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFirstRecoveryTimestampOf",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGuardiansOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getGuardiansThresholdOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNonce",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecoveryCounterOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecoveryDelayOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSecretHashOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotedAddressByGuardian",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotesOfGuardianVotedAddress",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasReachedThreshold",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isGuardianOf",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverAccess",
    values: [AddressLike, AddressLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeGuardian",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGuardiansThreshold",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRecoveryDelay",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRecoverySecretHash",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voteForRecovery",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "COMMITMEMT_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_RECOVERY_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "batchCalls", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelRecoveryProcess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitToRecover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeRelayCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeRelayCallBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommitmentInfoOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFirstRecoveryTimestampOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGuardiansOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGuardiansThresholdOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRecoveryCounterOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecoveryDelayOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSecretHashOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVotedAddressByGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVotesOfGuardianVotedAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasReachedThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isGuardianOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGuardiansThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRecoveryDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRecoverySecretHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteForRecovery",
    data: BytesLike
  ): Result;
}

export namespace GuardianAddedEvent {
  export type InputTuple = [account: AddressLike, guardian: AddressLike];
  export type OutputTuple = [account: string, guardian: string];
  export interface OutputObject {
    account: string;
    guardian: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GuardianRemovedEvent {
  export type InputTuple = [account: AddressLike, guardian: AddressLike];
  export type OutputTuple = [account: string, guardian: string];
  export interface OutputObject {
    account: string;
    guardian: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GuardianVotedForEvent {
  export type InputTuple = [
    account: AddressLike,
    recoveryCounter: BigNumberish,
    guardian: AddressLike,
    guardianVotedAddress: AddressLike
  ];
  export type OutputTuple = [
    account: string,
    recoveryCounter: bigint,
    guardian: string,
    guardianVotedAddress: string
  ];
  export interface OutputObject {
    account: string;
    recoveryCounter: bigint;
    guardian: string;
    guardianVotedAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GuardiansThresholdChangedEvent {
  export type InputTuple = [
    account: AddressLike,
    guardianThreshold: BigNumberish
  ];
  export type OutputTuple = [account: string, guardianThreshold: bigint];
  export interface OutputObject {
    account: string;
    guardianThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryCancelledEvent {
  export type InputTuple = [
    account: AddressLike,
    previousRecoveryCounter: BigNumberish
  ];
  export type OutputTuple = [account: string, previousRecoveryCounter: bigint];
  export interface OutputObject {
    account: string;
    previousRecoveryCounter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryDelayChangedEvent {
  export type InputTuple = [account: AddressLike, recoveryDelay: BigNumberish];
  export type OutputTuple = [account: string, recoveryDelay: bigint];
  export interface OutputObject {
    account: string;
    recoveryDelay: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryProcessSuccessfulEvent {
  export type InputTuple = [
    account: AddressLike,
    recoveryCounter: BigNumberish,
    guardianVotedAddress: AddressLike,
    calldataExecuted: BytesLike
  ];
  export type OutputTuple = [
    account: string,
    recoveryCounter: bigint,
    guardianVotedAddress: string,
    calldataExecuted: string
  ];
  export interface OutputObject {
    account: string;
    recoveryCounter: bigint;
    guardianVotedAddress: string;
    calldataExecuted: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecretHashChangedEvent {
  export type InputTuple = [account: AddressLike, secretHash: BytesLike];
  export type OutputTuple = [account: string, secretHash: string];
  export interface OutputObject {
    account: string;
    secretHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecretHashCommittedEvent {
  export type InputTuple = [
    account: AddressLike,
    recoveryCounter: BigNumberish,
    committedBy: AddressLike,
    commitment: BytesLike
  ];
  export type OutputTuple = [
    account: string,
    recoveryCounter: bigint,
    committedBy: string,
    commitment: string
  ];
  export interface OutputObject {
    account: string;
    recoveryCounter: bigint;
    committedBy: string;
    commitment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LSP11SocialRecovery extends BaseContract {
  connect(runner?: ContractRunner | null): LSP11SocialRecovery;
  waitForDeployment(): Promise<this>;

  interface: LSP11SocialRecoveryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COMMITMEMT_DELAY: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_RECOVERY_DELAY: TypedContractMethod<[], [bigint], "view">;

  addGuardian: TypedContractMethod<
    [account: AddressLike, newGuardian: AddressLike],
    [void],
    "nonpayable"
  >;

  batchCalls: TypedContractMethod<
    [data: BytesLike[]],
    [string[]],
    "nonpayable"
  >;

  cancelRecoveryProcess: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  commitToRecover: TypedContractMethod<
    [account: AddressLike, votedAddress: AddressLike, commitment: BytesLike],
    [void],
    "nonpayable"
  >;

  executeRelayCall: TypedContractMethod<
    [
      signature: BytesLike,
      nonce: BigNumberish,
      validityTimestamps: BigNumberish,
      payload: BytesLike
    ],
    [string],
    "payable"
  >;

  executeRelayCallBatch: TypedContractMethod<
    [
      signatures: BytesLike[],
      nonces: BigNumberish[],
      validityTimestamps: BigNumberish[],
      values: BigNumberish[],
      payloads: BytesLike[]
    ],
    [string[]],
    "payable"
  >;

  getCommitmentInfoOf: TypedContractMethod<
    [
      account: AddressLike,
      recoveryCounter: BigNumberish,
      committedBy: AddressLike
    ],
    [[string, bigint]],
    "view"
  >;

  getFirstRecoveryTimestampOf: TypedContractMethod<
    [account: AddressLike, recoveryCounter: BigNumberish],
    [bigint],
    "view"
  >;

  getGuardiansOf: TypedContractMethod<
    [account: AddressLike],
    [string[]],
    "view"
  >;

  getGuardiansThresholdOf: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  getNonce: TypedContractMethod<
    [from: AddressLike, channelId: BigNumberish],
    [bigint],
    "view"
  >;

  getRecoveryCounterOf: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  getRecoveryDelayOf: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  getSecretHashOf: TypedContractMethod<
    [account: AddressLike],
    [string],
    "view"
  >;

  getVotedAddressByGuardian: TypedContractMethod<
    [
      account: AddressLike,
      recoveryCounter: BigNumberish,
      guardian: AddressLike
    ],
    [string],
    "view"
  >;

  getVotesOfGuardianVotedAddress: TypedContractMethod<
    [
      account: AddressLike,
      recoveryCounter: BigNumberish,
      votedAddress: AddressLike
    ],
    [bigint],
    "view"
  >;

  hasReachedThreshold: TypedContractMethod<
    [
      account: AddressLike,
      recoveryCounter: BigNumberish,
      votedAddress: AddressLike
    ],
    [boolean],
    "view"
  >;

  isGuardianOf: TypedContractMethod<
    [account: AddressLike, guardianAddress: AddressLike],
    [boolean],
    "view"
  >;

  recoverAccess: TypedContractMethod<
    [
      account: AddressLike,
      votedAddress: AddressLike,
      secretHash: BytesLike,
      newSecretHash: BytesLike,
      calldataToExecute: BytesLike
    ],
    [string],
    "payable"
  >;

  removeGuardian: TypedContractMethod<
    [account: AddressLike, existingGuardian: AddressLike],
    [void],
    "nonpayable"
  >;

  setGuardiansThreshold: TypedContractMethod<
    [account: AddressLike, newThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRecoveryDelay: TypedContractMethod<
    [account: AddressLike, recoveryDelay: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRecoverySecretHash: TypedContractMethod<
    [account: AddressLike, newRecoverSecretHash: BytesLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  voteForRecovery: TypedContractMethod<
    [
      account: AddressLike,
      guardian: AddressLike,
      guardianVotedAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COMMITMEMT_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_RECOVERY_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addGuardian"
  ): TypedContractMethod<
    [account: AddressLike, newGuardian: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchCalls"
  ): TypedContractMethod<[data: BytesLike[]], [string[]], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelRecoveryProcess"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "commitToRecover"
  ): TypedContractMethod<
    [account: AddressLike, votedAddress: AddressLike, commitment: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeRelayCall"
  ): TypedContractMethod<
    [
      signature: BytesLike,
      nonce: BigNumberish,
      validityTimestamps: BigNumberish,
      payload: BytesLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "executeRelayCallBatch"
  ): TypedContractMethod<
    [
      signatures: BytesLike[],
      nonces: BigNumberish[],
      validityTimestamps: BigNumberish[],
      values: BigNumberish[],
      payloads: BytesLike[]
    ],
    [string[]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getCommitmentInfoOf"
  ): TypedContractMethod<
    [
      account: AddressLike,
      recoveryCounter: BigNumberish,
      committedBy: AddressLike
    ],
    [[string, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFirstRecoveryTimestampOf"
  ): TypedContractMethod<
    [account: AddressLike, recoveryCounter: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGuardiansOf"
  ): TypedContractMethod<[account: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getGuardiansThresholdOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNonce"
  ): TypedContractMethod<
    [from: AddressLike, channelId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecoveryCounterOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRecoveryDelayOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSecretHashOf"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getVotedAddressByGuardian"
  ): TypedContractMethod<
    [
      account: AddressLike,
      recoveryCounter: BigNumberish,
      guardian: AddressLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVotesOfGuardianVotedAddress"
  ): TypedContractMethod<
    [
      account: AddressLike,
      recoveryCounter: BigNumberish,
      votedAddress: AddressLike
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasReachedThreshold"
  ): TypedContractMethod<
    [
      account: AddressLike,
      recoveryCounter: BigNumberish,
      votedAddress: AddressLike
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isGuardianOf"
  ): TypedContractMethod<
    [account: AddressLike, guardianAddress: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "recoverAccess"
  ): TypedContractMethod<
    [
      account: AddressLike,
      votedAddress: AddressLike,
      secretHash: BytesLike,
      newSecretHash: BytesLike,
      calldataToExecute: BytesLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "removeGuardian"
  ): TypedContractMethod<
    [account: AddressLike, existingGuardian: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGuardiansThreshold"
  ): TypedContractMethod<
    [account: AddressLike, newThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRecoveryDelay"
  ): TypedContractMethod<
    [account: AddressLike, recoveryDelay: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRecoverySecretHash"
  ): TypedContractMethod<
    [account: AddressLike, newRecoverSecretHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "voteForRecovery"
  ): TypedContractMethod<
    [
      account: AddressLike,
      guardian: AddressLike,
      guardianVotedAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "GuardianAdded"
  ): TypedContractEvent<
    GuardianAddedEvent.InputTuple,
    GuardianAddedEvent.OutputTuple,
    GuardianAddedEvent.OutputObject
  >;
  getEvent(
    key: "GuardianRemoved"
  ): TypedContractEvent<
    GuardianRemovedEvent.InputTuple,
    GuardianRemovedEvent.OutputTuple,
    GuardianRemovedEvent.OutputObject
  >;
  getEvent(
    key: "GuardianVotedFor"
  ): TypedContractEvent<
    GuardianVotedForEvent.InputTuple,
    GuardianVotedForEvent.OutputTuple,
    GuardianVotedForEvent.OutputObject
  >;
  getEvent(
    key: "GuardiansThresholdChanged"
  ): TypedContractEvent<
    GuardiansThresholdChangedEvent.InputTuple,
    GuardiansThresholdChangedEvent.OutputTuple,
    GuardiansThresholdChangedEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryCancelled"
  ): TypedContractEvent<
    RecoveryCancelledEvent.InputTuple,
    RecoveryCancelledEvent.OutputTuple,
    RecoveryCancelledEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryDelayChanged"
  ): TypedContractEvent<
    RecoveryDelayChangedEvent.InputTuple,
    RecoveryDelayChangedEvent.OutputTuple,
    RecoveryDelayChangedEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryProcessSuccessful"
  ): TypedContractEvent<
    RecoveryProcessSuccessfulEvent.InputTuple,
    RecoveryProcessSuccessfulEvent.OutputTuple,
    RecoveryProcessSuccessfulEvent.OutputObject
  >;
  getEvent(
    key: "SecretHashChanged"
  ): TypedContractEvent<
    SecretHashChangedEvent.InputTuple,
    SecretHashChangedEvent.OutputTuple,
    SecretHashChangedEvent.OutputObject
  >;
  getEvent(
    key: "SecretHashCommitted"
  ): TypedContractEvent<
    SecretHashCommittedEvent.InputTuple,
    SecretHashCommittedEvent.OutputTuple,
    SecretHashCommittedEvent.OutputObject
  >;

  filters: {
    "GuardianAdded(address,address)": TypedContractEvent<
      GuardianAddedEvent.InputTuple,
      GuardianAddedEvent.OutputTuple,
      GuardianAddedEvent.OutputObject
    >;
    GuardianAdded: TypedContractEvent<
      GuardianAddedEvent.InputTuple,
      GuardianAddedEvent.OutputTuple,
      GuardianAddedEvent.OutputObject
    >;

    "GuardianRemoved(address,address)": TypedContractEvent<
      GuardianRemovedEvent.InputTuple,
      GuardianRemovedEvent.OutputTuple,
      GuardianRemovedEvent.OutputObject
    >;
    GuardianRemoved: TypedContractEvent<
      GuardianRemovedEvent.InputTuple,
      GuardianRemovedEvent.OutputTuple,
      GuardianRemovedEvent.OutputObject
    >;

    "GuardianVotedFor(address,uint256,address,address)": TypedContractEvent<
      GuardianVotedForEvent.InputTuple,
      GuardianVotedForEvent.OutputTuple,
      GuardianVotedForEvent.OutputObject
    >;
    GuardianVotedFor: TypedContractEvent<
      GuardianVotedForEvent.InputTuple,
      GuardianVotedForEvent.OutputTuple,
      GuardianVotedForEvent.OutputObject
    >;

    "GuardiansThresholdChanged(address,uint256)": TypedContractEvent<
      GuardiansThresholdChangedEvent.InputTuple,
      GuardiansThresholdChangedEvent.OutputTuple,
      GuardiansThresholdChangedEvent.OutputObject
    >;
    GuardiansThresholdChanged: TypedContractEvent<
      GuardiansThresholdChangedEvent.InputTuple,
      GuardiansThresholdChangedEvent.OutputTuple,
      GuardiansThresholdChangedEvent.OutputObject
    >;

    "RecoveryCancelled(address,uint256)": TypedContractEvent<
      RecoveryCancelledEvent.InputTuple,
      RecoveryCancelledEvent.OutputTuple,
      RecoveryCancelledEvent.OutputObject
    >;
    RecoveryCancelled: TypedContractEvent<
      RecoveryCancelledEvent.InputTuple,
      RecoveryCancelledEvent.OutputTuple,
      RecoveryCancelledEvent.OutputObject
    >;

    "RecoveryDelayChanged(address,uint256)": TypedContractEvent<
      RecoveryDelayChangedEvent.InputTuple,
      RecoveryDelayChangedEvent.OutputTuple,
      RecoveryDelayChangedEvent.OutputObject
    >;
    RecoveryDelayChanged: TypedContractEvent<
      RecoveryDelayChangedEvent.InputTuple,
      RecoveryDelayChangedEvent.OutputTuple,
      RecoveryDelayChangedEvent.OutputObject
    >;

    "RecoveryProcessSuccessful(address,uint256,address,bytes)": TypedContractEvent<
      RecoveryProcessSuccessfulEvent.InputTuple,
      RecoveryProcessSuccessfulEvent.OutputTuple,
      RecoveryProcessSuccessfulEvent.OutputObject
    >;
    RecoveryProcessSuccessful: TypedContractEvent<
      RecoveryProcessSuccessfulEvent.InputTuple,
      RecoveryProcessSuccessfulEvent.OutputTuple,
      RecoveryProcessSuccessfulEvent.OutputObject
    >;

    "SecretHashChanged(address,bytes32)": TypedContractEvent<
      SecretHashChangedEvent.InputTuple,
      SecretHashChangedEvent.OutputTuple,
      SecretHashChangedEvent.OutputObject
    >;
    SecretHashChanged: TypedContractEvent<
      SecretHashChangedEvent.InputTuple,
      SecretHashChangedEvent.OutputTuple,
      SecretHashChangedEvent.OutputObject
    >;

    "SecretHashCommitted(address,uint256,address,bytes32)": TypedContractEvent<
      SecretHashCommittedEvent.InputTuple,
      SecretHashCommittedEvent.OutputTuple,
      SecretHashCommittedEvent.OutputObject
    >;
    SecretHashCommitted: TypedContractEvent<
      SecretHashCommittedEvent.InputTuple,
      SecretHashCommittedEvent.OutputTuple,
      SecretHashCommittedEvent.OutputObject
    >;
  };
}
