/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface LSP26FollowerSystemInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "follow"
      | "followBatch"
      | "followerCount"
      | "followingCount"
      | "getFollowersByIndex"
      | "getFollowsByIndex"
      | "isFollowing"
      | "unfollow"
      | "unfollowBatch"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Follow" | "Unfollow"): EventFragment;

  encodeFunctionData(functionFragment: "follow", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "followBatch",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "followerCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "followingCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFollowersByIndex",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFollowsByIndex",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isFollowing",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unfollow",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unfollowBatch",
    values: [AddressLike[]]
  ): string;

  decodeFunctionResult(functionFragment: "follow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "followBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "followerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "followingCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFollowersByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFollowsByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isFollowing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unfollow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unfollowBatch",
    data: BytesLike
  ): Result;
}

export namespace FollowEvent {
  export type InputTuple = [follower: AddressLike, addr: AddressLike];
  export type OutputTuple = [follower: string, addr: string];
  export interface OutputObject {
    follower: string;
    addr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnfollowEvent {
  export type InputTuple = [unfollower: AddressLike, addr: AddressLike];
  export type OutputTuple = [unfollower: string, addr: string];
  export interface OutputObject {
    unfollower: string;
    addr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LSP26FollowerSystem extends BaseContract {
  connect(runner?: ContractRunner | null): LSP26FollowerSystem;
  waitForDeployment(): Promise<this>;

  interface: LSP26FollowerSystemInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  follow: TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;

  followBatch: TypedContractMethod<
    [addresses: AddressLike[]],
    [void],
    "nonpayable"
  >;

  followerCount: TypedContractMethod<[addr: AddressLike], [bigint], "view">;

  followingCount: TypedContractMethod<[addr: AddressLike], [bigint], "view">;

  getFollowersByIndex: TypedContractMethod<
    [addr: AddressLike, startIndex: BigNumberish, endIndex: BigNumberish],
    [string[]],
    "view"
  >;

  getFollowsByIndex: TypedContractMethod<
    [addr: AddressLike, startIndex: BigNumberish, endIndex: BigNumberish],
    [string[]],
    "view"
  >;

  isFollowing: TypedContractMethod<
    [follower: AddressLike, addr: AddressLike],
    [boolean],
    "view"
  >;

  unfollow: TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;

  unfollowBatch: TypedContractMethod<
    [addresses: AddressLike[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "follow"
  ): TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "followBatch"
  ): TypedContractMethod<[addresses: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "followerCount"
  ): TypedContractMethod<[addr: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "followingCount"
  ): TypedContractMethod<[addr: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFollowersByIndex"
  ): TypedContractMethod<
    [addr: AddressLike, startIndex: BigNumberish, endIndex: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFollowsByIndex"
  ): TypedContractMethod<
    [addr: AddressLike, startIndex: BigNumberish, endIndex: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isFollowing"
  ): TypedContractMethod<
    [follower: AddressLike, addr: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "unfollow"
  ): TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unfollowBatch"
  ): TypedContractMethod<[addresses: AddressLike[]], [void], "nonpayable">;

  getEvent(
    key: "Follow"
  ): TypedContractEvent<
    FollowEvent.InputTuple,
    FollowEvent.OutputTuple,
    FollowEvent.OutputObject
  >;
  getEvent(
    key: "Unfollow"
  ): TypedContractEvent<
    UnfollowEvent.InputTuple,
    UnfollowEvent.OutputTuple,
    UnfollowEvent.OutputObject
  >;

  filters: {
    "Follow(address,address)": TypedContractEvent<
      FollowEvent.InputTuple,
      FollowEvent.OutputTuple,
      FollowEvent.OutputObject
    >;
    Follow: TypedContractEvent<
      FollowEvent.InputTuple,
      FollowEvent.OutputTuple,
      FollowEvent.OutputObject
    >;

    "Unfollow(address,address)": TypedContractEvent<
      UnfollowEvent.InputTuple,
      UnfollowEvent.OutputTuple,
      UnfollowEvent.OutputObject
    >;
    Unfollow: TypedContractEvent<
      UnfollowEvent.InputTuple,
      UnfollowEvent.OutputTuple,
      UnfollowEvent.OutputObject
    >;
  };
}
